# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2012-2013
  project: Extension Name
  version: x.y
  release: x.y.z
  intersphinx_mapping:
    # Add more mappings depending on what manual you want to link
    # Remove entirely if you don't need cross-linking
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
  latex_documents:
  - - Index
    - <extension_key>.tex
    - Extension Name
    - Your Name
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
